FROM ubuntu:bionic

MAINTAINER Phocean <jc@phocean.net>

ENV DEBIAN_FRONTEND=noninteractive \
    HOME=/home/anon \
    GPG_KEY=A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89

WORKDIR $HOME

RUN apt-get update &&\
    apt-get install -y --no-install-recommends apt-transport-https ca-certificates gpg dirmngr &&\
    printf "deb https://deb.torproject.org/torproject.org bionic main\ndeb-src https://deb.torproject.org/torproject. org bionic main" > /etc/apt/sources.list.d/tor.list &&\
    export GNUPGHOME="$(mktemp -d)" &&\
    for server in ha.pool.sks-keyservers.net \
              hkp://p80.pool.sks-keyservers.net:80 \
              keyserver.ubuntu.com \
              hkp://keyserver.ubuntu.com:80 \
              pgp.mit.edu; do \
      gpg --keyserver "$server" --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 && break || echo "Trying new server..."; \
    done &&\
    apt-get -y --no-install-recommends install tor torbrowser-launcher &&\
    rm -rf /var/lib/apt/lists/* &&\
    mkdir -p $HOME/Downloads &&\
    useradd -u 1000 anon &&\
    chown -R anon:anon $HOME

VOLUME $HOME/Downloads

#USER anon

CMD start-tor-browser
